name = "PseudoPotentials"
uuid = "d363707c-1fc7-11e9-39df-3fc87e3120f4"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
AtomicLevels = "10933b4c-d60f-11e8-1fc6-bd9035a249a1"
AtomicPotentials = "eac66916-230f-11e9-03e5-b9a8fe2fc74a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
